import Link from 'next/link';
import { CheckCircle2, FileCheck2, ArrowRight, ClipboardCheck, ShieldCheck } from 'lucide-react';
import NicheLeadForm from '@/components/NicheLeadForm';
import { Footer } from '@/components/Footer';

export const metadata = {
  title: 'Commercial Trucking Insurance Requirements (2026 Guide)',
  description: 'Learn common commercial trucking insurance requirements, federal filings, cargo coverage, documents, and next steps for new and established carriers.',
  alternates: { canonical: 'https://www.truckcoverageexperts.com/trucking-insurance-requirements' },
};

const requirements = [
  ['Primary liability', 'Commercial auto liability protects against covered third-party bodily injury and property damage claims. Required limits can depend on authority, commodity, vehicle, and operation.'],
  ['Federal or state filings', 'Motor carriers may need insurance filings connected to operating authority. Review the applicable federal or state requirement rather than assuming every carrier has the same filing.'],
  ['Cargo coverage', 'Motor truck cargo coverage may be required by a broker, shipper, contract, or commodity. Limits and exclusions should match what the carrier actually transports.'],
  ['Physical damage', 'Collision and comprehensive coverage can be reviewed for owned, financed, or leased trucks and trailers. Vehicle value, deductibles, and lender requirements matter.'],
  ['Additional business coverage', 'Depending on the operation, general liability, hired and non-owned auto, trailer interchange, occupational accident, or workers compensation may also need review.'],
];

const documents = ['Driver list and motor vehicle records', 'Vehicle year, VIN, value, and equipment schedule', 'Cargo description and operating radius', 'DOT/MC authority information', 'Prior declarations page and loss runs', 'Broker, shipper, or contract insurance requirements'];

export default function TruckingInsuranceRequirementsPage() {
  return <div className="min-h-screen bg-slate-950 text-slate-200"><nav className="border-b border-slate-800 bg-slate-950/95 sticky top-0 z-50"><div className="max-w-7xl mx-auto px-6 h-16 flex items-center justify-between"><Link href="/" className="text-white font-black tracking-tight">TRUCK COVERAGE EXPERTS</Link><Link href="#review" className="bg-blue-600 hover:bg-blue-500 text-white px-4 py-2 rounded text-sm font-bold">Request a review</Link></div></nav><main>
    <section className="border-b border-slate-800 bg-gradient-to-br from-blue-950/60 via-slate-950 to-slate-950"><div className="max-w-7xl mx-auto px-6 py-20 grid lg:grid-cols-2 gap-12 items-center"><div><div className="inline-flex items-center gap-2 text-blue-300 text-xs uppercase tracking-widest font-bold mb-6"><ClipboardCheck className="w-4 h-4" /> Carrier requirements guide</div><h1 className="text-5xl md:text-6xl font-black text-white leading-tight mb-6">Commercial Trucking Insurance Requirements</h1><p className="text-xl text-slate-300 leading-relaxed mb-8">Understand the coverage, filings, and documents commonly reviewed when starting or operating a trucking company. Requirements vary by authority, cargo, vehicle, routes, contracts, and state.</p><div className="flex flex-wrap gap-3"><Link href="#checklist" className="inline-flex items-center gap-2 bg-blue-600 hover:bg-blue-500 text-white font-bold px-6 py-4 rounded-xl">View the checklist <ArrowRight className="w-4 h-4" /></Link><Link href="/filing/bmc91x-federal-filing-fmsca" className="border border-slate-700 hover:border-blue-400 px-6 py-4 rounded-xl">Review BMC-91X</Link></div></div><div id="review"><NicheLeadForm stateName="your state" nicheName="Commercial Trucking Insurance Requirements" /></div></div></section>

    <section id="checklist" className="max-w-7xl mx-auto px-6 py-16"><div className="max-w-3xl mb-10"><h2 className="text-3xl font-black text-white mb-4">What insurance does a trucking company need?</h2><p className="text-slate-400 leading-relaxed">There is no single policy that fits every motor carrier. A useful requirements review starts with how the business operates, what it hauls, whose authority it uses, and what contracts require.</p></div><div className="grid md:grid-cols-2 lg:grid-cols-3 gap-5">{requirements.map(([title, body]) => <article key={title} className="bg-slate-900 border border-slate-800 rounded-2xl p-6"><ShieldCheck className="text-blue-400 mb-4" /><h3 className="text-xl font-bold text-white mb-3">{title}</h3><p className="text-slate-400 leading-relaxed">{body}</p></article>)}</div></section>

    <section className="bg-slate-900/60 border-y border-slate-800"><div className="max-w-7xl mx-auto px-6 py-16 grid lg:grid-cols-2 gap-12"><div><h2 className="text-3xl font-black text-white mb-5">Documents commonly needed for a quote</h2><p className="text-slate-400 leading-relaxed mb-6">Preparing these details can make the review faster and helps avoid incomplete submissions:</p><ul className="space-y-3">{documents.map(item => <li key={item} className="flex gap-3 text-slate-300"><CheckCircle2 className="w-5 h-5 text-emerald-400 shrink-0" />{item}</li>)}</ul></div><div><h2 className="text-3xl font-black text-white mb-5">Federal filing starting points</h2><p className="text-slate-400 leading-relaxed mb-6">BMC-91X, BMC-34, BOC-3, and state filings are different topics. The applicable filing depends on the carrier and operation.</p><div className="space-y-3"><Link href="/filing/bmc91x-federal-filing-fmsca" className="block border border-slate-700 rounded-xl p-4 hover:border-blue-400"><FileCheck2 className="inline w-5 h-5 text-blue-400 mr-3" /><span className="font-bold text-white">BMC-91X federal insurance filing</span></Link><Link href="/filings" className="block border border-slate-700 rounded-xl p-4 hover:border-blue-400"><FileCheck2 className="inline w-5 h-5 text-blue-400 mr-3" /><span className="font-bold text-white">Browse filing requirements</span></Link><Link href="/dot-insurance-lookup" className="block border border-slate-700 rounded-xl p-4 hover:border-blue-400"><FileCheck2 className="inline w-5 h-5 text-blue-400 mr-3" /><span className="font-bold text-white">Check DOT insurance information</span></Link></div></div></div></section>

    <section className="max-w-7xl mx-auto px-6 py-16"><h2 className="text-3xl font-black text-white mb-8">Requirements by trucking operation</h2><div className="grid md:grid-cols-2 lg:grid-cols-4 gap-4">{[['Box truck', '/box-truck-insurance'], ['Hot shot', '/hot-shot'], ['Car hauler', '/insurance/auto-hauler-car-carrier-insurance'], ['Specialized equipment', '/insurance']].map(([name, href]) => <Link key={href} href={href} className="bg-slate-900 border border-slate-800 rounded-xl p-5 hover:border-blue-400"><span className="font-bold text-white">{name} insurance</span><span className="block text-sm text-slate-400 mt-2">Review coverage and requirements <ArrowRight className="inline w-4 h-4" /></span></Link>)}</div></section>

    <section className="max-w-4xl mx-auto px-6 pb-20"><h2 className="text-3xl font-black text-white mb-8">Trucking insurance requirement questions</h2>{[['What are the minimum commercial truck insurance requirements?', 'Minimums vary by authority, commodity, vehicle, and applicable federal or state rules. Broker and shipper contracts may request limits above a legal minimum.'], ['Does every trucking company need an FMCSA filing?', 'Not every operation has the same federal filing obligations. Interstate motor carriers should review their authority and commodity requirements with a qualified professional.'], ['What insurance does a new authority need?', 'A new authority typically needs a coverage and filing review before operating. The exact requirements depend on the operation, cargo, vehicles, routes, and authority status.'], ['Can requirements differ by state?', 'Yes. State and federal requirements can differ, especially for intrastate operations, permits, filings, and special commodities.']].map(([q, a]) => <details key={q} className="border-b border-slate-800 py-5"><summary className="cursor-pointer font-bold text-white text-lg">{q}</summary><p className="text-slate-400 leading-relaxed mt-3">{a}</p></details>)}</section>
  </main><Footer /></div>;
}
