import Link from 'next/link';
import { ClipboardCheck, ArrowRight } from 'lucide-react';
import ReadinessTool from '@/components/ReadinessTool';
import { Footer } from '@/components/Footer';

export const metadata = {
  title: 'Free Trucking Insurance Readiness Checklist',
  description: 'Generate a free trucking insurance readiness checklist based on your equipment, cargo, authority status, and operating radius before requesting a quote.',
  alternates: { canonical: 'https://www.truckcoverageexperts.com/trucking-insurance-readiness' },
};

export default function TruckingInsuranceReadinessPage() {
  return <div className="min-h-screen bg-slate-950 text-slate-200"><nav className="border-b border-slate-800 bg-slate-950/95 sticky top-0 z-50"><div className="max-w-7xl mx-auto px-6 h-16 flex items-center justify-between"><Link href="/" className="text-white font-black tracking-tight">TRUCK COVERAGE EXPERTS</Link><Link href="/quote" className="bg-blue-600 hover:bg-blue-500 text-white px-4 py-2 rounded text-sm font-bold">Quote review</Link></div></nav><main><section className="bg-gradient-to-br from-blue-950/60 via-slate-950 to-slate-950 border-b border-slate-800"><div className="max-w-7xl mx-auto px-6 py-20 grid lg:grid-cols-2 gap-12 items-center"><div><div className="inline-flex items-center gap-2 text-blue-300 text-xs uppercase tracking-widest font-bold mb-6"><ClipboardCheck className="w-4 h-4" /> Free preparation tool</div><h1 className="text-5xl md:text-6xl font-black text-white leading-tight mb-6">Trucking Insurance Readiness Checklist</h1><p className="text-xl text-slate-300 leading-relaxed mb-8">Get a practical starting checklist for your commercial trucking operation before you request insurance. Choose your equipment, cargo, authority status, and operating radius.</p><Link href="#tool" className="inline-flex items-center gap-2 bg-blue-600 hover:bg-blue-500 text-white font-bold px-6 py-4 rounded-xl">Start the free checklist <ArrowRight className="w-4 h-4" /></Link></div><div id="tool"><ReadinessTool /></div></div></section><section className="max-w-5xl mx-auto px-6 py-16"><h2 className="text-3xl font-black text-white mb-5">What the checklist helps you prepare</h2><p className="text-slate-400 leading-relaxed mb-8">A complete submission can help a licensed professional understand your operation and identify what needs further review. Prepare your driver list, vehicle schedule, cargo description, operating states, authority information, and prior loss history when available.</p><div className="grid md:grid-cols-3 gap-5"><div className="bg-slate-900 border border-slate-800 rounded-xl p-6"><h3 className="font-bold text-white mb-2">Coverage discussion</h3><p className="text-sm text-slate-400">Liability, cargo, physical damage, and additional operational exposures.</p></div><div className="bg-slate-900 border border-slate-800 rounded-xl p-6"><h3 className="font-bold text-white mb-2">Filing preparation</h3><p className="text-sm text-slate-400">DOT/MC information, applicable filings, certificates, and contract limits.</p></div><div className="bg-slate-900 border border-slate-800 rounded-xl p-6"><h3 className="font-bold text-white mb-2">Faster review</h3><p className="text-sm text-slate-400">Organized details reduce back-and-forth when requesting available options.</p></div></div></section></main><Footer /></div>;
}
