import Link from 'next/link';
import { ArrowRight, CheckCircle2, ClipboardList, FileText, ShieldCheck } from 'lucide-react';
import NicheLeadForm from '@/components/NicheLeadForm';
import { Footer } from '@/components/Footer';
import { SiteHeader } from '@/components/SiteHeader';

export const metadata = {
  title: 'New Authority Trucking Insurance: Startup Guide (2026)',
  description: 'Learn what new trucking companies should prepare for commercial insurance, authority filings, cargo coverage, documents, and a first quote review.',
  alternates: { canonical: 'https://www.truckcoverageexperts.com/new-authority-insurance' },
};

const checklist = ['Choose the equipment and operating model', 'Confirm DOT/MC authority status and operating states', 'Describe cargo, routes, radius, and broker relationships', 'Prepare driver, vehicle, loss-run, and business documents', 'Review liability, cargo, physical damage, and additional coverage', 'Confirm filing and certificate requirements before operating'];
const faqs = [
  ['What insurance does a new trucking authority need?', 'A new authority should review commercial auto liability, applicable filings, cargo, physical damage, and any broker or shipper requirements. The exact combination depends on the equipment, cargo, routes, and authority.'],
  ['How do I prepare for a new-authority insurance quote?', 'Prepare DOT/MC information, authority status, driver and vehicle details, cargo, operating radius, states, loss history when available, and any contract limits or certificate instructions.'],
  ['Can I operate before my insurance filing is active?', 'Do not assume a policy or application means your authority is ready to operate. Confirm the required coverage, filing transmission, authority status, and operating permissions before accepting loads.'],
];
const faqSchema = { '@context': 'https://schema.org', '@type': 'FAQPage', mainEntity: faqs.map(([question, answer]) => ({ '@type': 'Question', name: question, acceptedAnswer: { '@type': 'Answer', text: answer } })) };

export default function NewAuthorityInsurancePage() {
  return <div className="min-h-screen bg-slate-950 text-slate-200"><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }} /><SiteHeader ctaHref="#review" ctaLabel="Request a review" /><main>
    <section className="border-b border-slate-800 bg-gradient-to-br from-amber-950/30 via-slate-950 to-slate-950"><div className="max-w-7xl mx-auto px-6 py-20 grid lg:grid-cols-2 gap-12 items-center"><div><div className="inline-flex items-center gap-2 text-amber-300 text-xs uppercase tracking-widest font-bold mb-6"><ClipboardList className="w-4 h-4" /> New carrier guide</div><h1 className="text-5xl md:text-6xl font-black text-white leading-tight mb-6">New Authority Trucking Insurance</h1><p className="text-xl text-slate-300 leading-relaxed mb-8">Starting a trucking company requires more than buying a truck and requesting a policy. Use this guide to organize your authority, equipment, cargo, documents, coverage discussion, and filing review.</p><div className="flex flex-wrap gap-3"><Link href="#checklist" className="inline-flex items-center gap-2 bg-blue-600 hover:bg-blue-500 text-white font-bold px-6 py-4 rounded-xl">View startup checklist <ArrowRight className="w-4 h-4" /></Link><Link href="/trucking-insurance-requirements" className="border border-slate-700 hover:border-blue-400 px-6 py-4 rounded-xl">Insurance requirements</Link><Link href="/trucking-insurance-readiness" className="border border-slate-700 hover:border-blue-400 px-6 py-4 rounded-xl">Free readiness checklist</Link></div></div><div id="review"><NicheLeadForm stateName="your state" nicheName="New Authority Trucking Insurance" /></div></div></section>
    <section id="checklist" className="max-w-7xl mx-auto px-6 py-16"><div className="max-w-3xl mb-10"><h2 className="text-3xl font-black text-white mb-4">New trucking company insurance checklist</h2><p className="text-slate-400 leading-relaxed">Underwriting and filing requirements vary. This checklist helps you prepare a complete review before accepting loads or activating operations.</p></div><div className="grid md:grid-cols-2 lg:grid-cols-3 gap-5">{checklist.map((item, index) => <div key={item} className="bg-slate-900 border border-slate-800 rounded-2xl p-6"><div className="text-amber-300 font-black text-sm mb-4">STEP {index + 1}</div><p className="flex gap-3 text-slate-300 leading-relaxed"><CheckCircle2 className="w-5 h-5 text-emerald-400 shrink-0" />{item}</p></div>)}</div></section>
    <section className="bg-slate-900/60 border-y border-slate-800"><div className="max-w-7xl mx-auto px-6 py-16 grid lg:grid-cols-2 gap-12"><div><h2 className="text-3xl font-black text-white mb-5">Coverage to discuss</h2><div className="space-y-4"><p className="text-slate-400 leading-relaxed"><strong className="text-white">Primary liability:</strong> Review commercial auto liability for covered third-party injury and property damage exposures.</p><p className="text-slate-400 leading-relaxed"><strong className="text-white">Cargo:</strong> Match motor truck cargo coverage to the commodities, values, contracts, and exclusions that apply to the operation.</p><p className="text-slate-400 leading-relaxed"><strong className="text-white">Physical damage:</strong> Consider the truck, trailer, lender requirements, vehicle value, and deductible.</p><p className="text-slate-400 leading-relaxed"><strong className="text-white">Additional coverage:</strong> Depending on the business, review general liability, trailer interchange, hired and non-owned auto, occupational accident, or workers compensation.</p></div></div><div><h2 className="text-3xl font-black text-white mb-5">Documents for a new-authority review</h2><ul className="space-y-3">{['Business legal name and entity information', 'DOT/MC numbers and authority status', 'Driver list, experience, and MVR information', 'Vehicle and trailer schedule with values', 'Cargo type, operating radius, and states', 'Broker or shipper contract requirements'].map(item => <li key={item} className="flex gap-3 text-slate-300"><FileText className="w-5 h-5 text-blue-400 shrink-0" />{item}</li>)}</ul></div></div></section>
    <section className="max-w-7xl mx-auto px-6 py-16"><h2 className="text-3xl font-black text-white mb-8">New-authority resources</h2><div className="grid md:grid-cols-2 lg:grid-cols-4 gap-5"><Link href="/filing/bmc91x-federal-filing-fmsca" className="bg-slate-900 border border-slate-800 rounded-xl p-6 hover:border-blue-400"><ShieldCheck className="text-blue-400 mb-4" /><h3 className="font-bold text-white mb-2">BMC-91X filing guide</h3><p className="text-sm text-slate-400">Understand the federal insurance filing topic separately from BOC-3.</p></Link><Link href="/trucking-insurance-readiness" className="bg-blue-950/40 border border-blue-800 rounded-xl p-6 hover:border-blue-400"><ClipboardList className="text-blue-300 mb-4" /><h3 className="font-bold text-white mb-2">Free readiness checklist</h3><p className="text-sm text-slate-400">Turn your authority, equipment, cargo, and document details into a practical next step.</p></Link><Link href="/box-truck-insurance" className="bg-slate-900 border border-slate-800 rounded-xl p-6 hover:border-blue-400"><ShieldCheck className="text-blue-400 mb-4" /><h3 className="font-bold text-white mb-2">Box truck insurance</h3><p className="text-sm text-slate-400">Review commercial coverage for delivery and straight-truck operations.</p></Link><Link href="/hot-shot" className="bg-slate-900 border border-slate-800 rounded-xl p-6 hover:border-blue-400"><ShieldCheck className="text-blue-400 mb-4" /><h3 className="font-bold text-white mb-2">Hot shot insurance</h3><p className="text-sm text-slate-400">Review pickup-and-trailer coverage and startup considerations.</p></Link></div></section>
    <section className="max-w-4xl mx-auto px-6 pb-20"><h2 className="text-3xl font-black text-white mb-8">New authority questions</h2>{faqs.map(([question, answer]) => <details key={question} className="border-b border-slate-800 py-5"><summary className="cursor-pointer font-bold text-white text-lg">{question}</summary><p className="text-slate-400 leading-relaxed mt-3">{answer}</p></details>)}</section>
  </main><Footer /></div>;
}
