import Link from 'next/link';
import { ArrowRight, CheckCircle2, FileCheck2, ShieldCheck, Truck } from 'lucide-react';
import NicheLeadForm from '@/components/NicheLeadForm';
import { Footer } from '@/components/Footer';

export const metadata = {
  title: 'Box Truck Insurance: Coverage, Cost & Quotes (2026)',
  description: 'Compare box truck insurance coverage, requirements, cost factors, and quote options for local delivery, freight, moving, and straight-truck businesses.',
  alternates: { canonical: 'https://www.truckcoverageexperts.com/box-truck-insurance' },
};

const faqs = [
  ['What insurance does a box truck business need?', 'Many box truck businesses review commercial auto liability, physical damage, motor truck cargo, and sometimes general liability, hired and non-owned auto, or workers compensation. The right combination depends on the work, vehicle, cargo, drivers, and contracts.'],
  ['How much does box truck insurance cost?', 'Pricing varies with vehicle value and weight, operating radius, cargo, driving history, experience, claims, authority age, and selected limits. A licensed professional can review those factors and available options rather than relying on a generic average.'],
  ['Do I need commercial insurance for a box truck?', 'If the vehicle is used for business, deliveries, freight, moving services, or contract work, a personal auto policy may not be appropriate. Commercial coverage should be reviewed before operating.'],
  ['Can I get box truck insurance without a CDL?', 'A CDL is not automatically required for every box truck. Requirements depend on the vehicle weight, configuration, and operation. Even when a CDL is not required, insurers may still review driver experience and motor vehicle records.'],
  ['What documents are needed for a quote?', 'Common underwriting information includes a driver list, vehicle year/value/VIN, operating radius, cargo description, loss history, authority details, and current declarations page if replacing coverage.'],
];

export default function BoxTruckInsuranceHub() {
  return <div className="min-h-screen bg-slate-950 text-slate-200">
    <nav className="border-b border-slate-800 bg-slate-950/95 sticky top-0 z-50"><div className="max-w-7xl mx-auto px-6 h-16 flex items-center justify-between"><Link href="/" className="text-white font-black tracking-tight">TRUCK COVERAGE EXPERTS</Link><Link href="#quote-review" className="bg-blue-600 hover:bg-blue-500 text-white px-4 py-2 rounded text-sm font-bold">Request a review</Link></div></nav>
    <main>
      <section className="relative overflow-hidden border-b border-slate-800"><div className="absolute inset-0 bg-gradient-to-br from-blue-950/50 via-slate-950 to-slate-950" /><div className="relative max-w-7xl mx-auto px-6 py-20 lg:py-28 grid lg:grid-cols-2 gap-12 items-center"><div><div className="inline-flex items-center gap-2 text-blue-300 text-xs uppercase tracking-widest font-bold mb-6"><Truck className="w-4 h-4" /> Commercial box truck coverage</div><h1 className="text-5xl md:text-6xl font-black text-white leading-tight mb-6">Box Truck Insurance for Your Business</h1><p className="text-xl leading-relaxed text-slate-300 mb-8">Review coverage for delivery routes, moving companies, freight carriers, contractors, and other straight-truck operations. Your quote depends on the truck, cargo, radius, drivers, and contracts—not just the vehicle type.</p><div className="flex flex-wrap gap-3"><Link href="#quote-review" className="inline-flex items-center gap-2 bg-blue-600 hover:bg-blue-500 text-white font-bold px-6 py-4 rounded-xl">Request a quote review <ArrowRight className="w-4 h-4" /></Link><Link href="/box-truck-insurance/texas" className="border border-slate-700 hover:border-blue-400 px-6 py-4 rounded-xl">See a state example</Link></div></div><div id="quote-review"><NicheLeadForm stateName="your state" nicheName="Box Truck Insurance" /></div></div></section>

      <section className="max-w-7xl mx-auto px-6 py-16"><div className="grid md:grid-cols-3 gap-6"><div className="bg-slate-900 border border-slate-800 rounded-2xl p-6"><ShieldCheck className="text-blue-400 mb-4" /><h2 className="text-xl font-bold text-white mb-3">Commercial auto liability</h2><p className="text-slate-400 leading-relaxed">Protects against covered third-party injury or property damage claims arising from business vehicle use. Limits may be shaped by contracts, authority, routes, and cargo.</p></div><div className="bg-slate-900 border border-slate-800 rounded-2xl p-6"><FileCheck2 className="text-emerald-400 mb-4" /><h2 className="text-xl font-bold text-white mb-3">Cargo and operations</h2><p className="text-slate-400 leading-relaxed">Motor truck cargo, loading and unloading, warehouse exposure, and hired or non-owned vehicles may matter depending on what you transport and how the work is performed.</p></div><div className="bg-slate-900 border border-slate-800 rounded-2xl p-6"><CheckCircle2 className="text-amber-400 mb-4" /><h2 className="text-xl font-bold text-white mb-3">Physical damage</h2><p className="text-slate-400 leading-relaxed">Collision and comprehensive coverage can be reviewed for the truck and permanently attached equipment. Vehicle value, financing, deductibles, and use affect the policy.</p></div></div></section>

      <section className="bg-slate-900/60 border-y border-slate-800"><div className="max-w-7xl mx-auto px-6 py-16 grid lg:grid-cols-2 gap-12"><div><h2 className="text-3xl font-black text-white mb-5">What affects box truck insurance cost?</h2><p className="text-slate-400 leading-relaxed mb-5">There is no reliable one-size-fits-all box truck insurance rate. Underwriters commonly consider:</p><ul className="space-y-3 text-slate-300">{['Vehicle type, weight, age, value, and radius', 'Cargo, delivery contracts, and loss exposure', 'Driver experience, MVRs, and claims history', 'Authority age and local versus interstate operation', 'Coverage limits, deductibles, and payment terms'].map(item => <li key={item} className="flex gap-3"><CheckCircle2 className="w-5 h-5 text-emerald-400 shrink-0" />{item}</li>)}</ul></div><div className="space-y-5"><h2 className="text-3xl font-black text-white">Explore box truck resources</h2><Link href="/insurance/car-hauler-insurance-cost" className="block bg-slate-900 border border-slate-700 rounded-xl p-5 hover:border-blue-400"><span className="font-bold text-white">Compare equipment insurance costs</span><span className="block text-sm text-slate-400 mt-2">Understand the factors that change commercial vehicle pricing.</span></Link><Link href="/box-truck-insurance/texas" className="block bg-slate-900 border border-slate-700 rounded-xl p-5 hover:border-blue-400"><span className="font-bold text-white">Review state-specific guidance</span><span className="block text-sm text-slate-400 mt-2">Start with Texas, then choose the state where your operation is based.</span></Link><Link href="/filing/bmc91x-federal-filing-fmsca" className="block bg-slate-900 border border-slate-700 rounded-xl p-5 hover:border-blue-400"><span className="font-bold text-white">Learn about BMC-91X filings</span><span className="block text-sm text-slate-400 mt-2">Review the federal filing starting point for applicable motor carriers.</span></Link></div></div></section>

      <section className="max-w-4xl mx-auto px-6 py-16"><h2 className="text-3xl font-black text-white mb-8">Box truck insurance questions</h2>{faqs.map(([question, answer]) => <details key={question} className="border-b border-slate-800 py-5"><summary className="cursor-pointer text-lg font-bold text-white">{question}</summary><p className="text-slate-400 leading-relaxed mt-3">{answer}</p></details>)}</section>
    </main><Footer />
  </div>;
}
