import Link from 'next/link';
import { ArrowRight, CheckCircle2, FileCheck2, SearchCheck, ShieldCheck } from 'lucide-react';
import NicheLeadForm from '@/components/NicheLeadForm';
import { Footer } from '@/components/Footer';

export const metadata = {
  title: 'DOT Insurance Requirements: Coverage & Filing Guide (2026)',
  description: 'Understand DOT insurance requirements, liability and cargo coverage, FMCSA filings, authority status, and the information to prepare for a commercial truck insurance review.',
  alternates: { canonical: 'https://www.truckcoverageexperts.com/dot-insurance-requirements' },
};

const steps = [
  ['Identify the operation', 'Confirm whether you operate interstate or intrastate, what equipment you use, what cargo you haul, and whether you operate under your own authority or another carrier’s authority.'],
  ['Check the applicable requirements', 'DOT and FMCSA requirements can depend on the carrier, commodity, vehicle, routes, and authority. Contractual limits from brokers and shippers may be different from regulatory minimums.'],
  ['Match coverage to the exposure', 'Review commercial auto liability, cargo, physical damage, and additional coverage with a licensed insurance professional. The policy should reflect the actual operation.'],
  ['Prepare the filing information', 'Have your DOT/MC information, insured name, limits, vehicle schedule, cargo, and effective date ready before requesting a filing review.'],
];

export default function DotInsuranceRequirementsPage() {
  return <div className="min-h-screen bg-slate-950 text-slate-200"><nav className="border-b border-slate-800 bg-slate-950/95 sticky top-0 z-50"><div className="max-w-7xl mx-auto px-6 h-16 flex items-center justify-between"><Link href="/" className="text-white font-black tracking-tight">TRUCK COVERAGE EXPERTS</Link><Link href="#review" className="bg-blue-600 hover:bg-blue-500 text-white px-4 py-2 rounded text-sm font-bold">Request a review</Link></div></nav><main>
    <section className="border-b border-slate-800 bg-gradient-to-br from-indigo-950/60 via-slate-950 to-slate-950"><div className="max-w-7xl mx-auto px-6 py-20 grid lg:grid-cols-2 gap-12 items-center"><div><div className="inline-flex items-center gap-2 text-blue-300 text-xs uppercase tracking-widest font-bold mb-6"><SearchCheck className="w-4 h-4" /> DOT compliance guide</div><h1 className="text-5xl md:text-6xl font-black text-white leading-tight mb-6">DOT Insurance Requirements for Trucking Companies</h1><p className="text-xl text-slate-300 leading-relaxed mb-8">Use this guide to understand the relationship between DOT registration, commercial insurance, financial responsibility, and federal filings. The exact requirement depends on your carrier profile and operation.</p><div className="flex flex-wrap gap-3"><Link href="#checklist" className="inline-flex items-center gap-2 bg-blue-600 hover:bg-blue-500 text-white font-bold px-6 py-4 rounded-xl">See the checklist <ArrowRight className="w-4 h-4" /></Link><Link href="/filing/bmc91x-federal-filing-fmsca" className="border border-slate-700 hover:border-blue-400 px-6 py-4 rounded-xl">BMC-91X guide</Link><Link href="/trucking-insurance-readiness" className="border border-slate-700 hover:border-blue-400 px-6 py-4 rounded-xl">Free readiness checklist</Link></div></div><div id="review"><NicheLeadForm stateName="your state" nicheName="DOT Insurance Requirements" /></div></div></section>

    <section id="checklist" className="max-w-7xl mx-auto px-6 py-16"><div className="max-w-3xl mb-10"><h2 className="text-3xl font-black text-white mb-4">How to review DOT insurance requirements</h2><p className="text-slate-400 leading-relaxed">A DOT number by itself does not tell you every coverage or filing obligation. Work through the operation details in order:</p></div><div className="grid md:grid-cols-2 gap-6">{steps.map(([title, body], index) => <article key={title} className="bg-slate-900 border border-slate-800 rounded-2xl p-7"><div className="text-blue-400 font-black text-sm mb-4">0{index + 1}</div><h3 className="text-xl font-bold text-white mb-3">{title}</h3><p className="text-slate-400 leading-relaxed">{body}</p></article>)}</div></section>

    <section className="bg-slate-900/60 border-y border-slate-800"><div className="max-w-7xl mx-auto px-6 py-16 grid lg:grid-cols-3 gap-6"><div className="bg-slate-900 border border-slate-800 rounded-2xl p-6"><ShieldCheck className="text-blue-400 mb-4" /><h2 className="text-xl font-bold text-white mb-3">Liability coverage</h2><p className="text-slate-400 leading-relaxed">Commercial auto liability is commonly reviewed for covered third-party injury and property damage claims. Limits may be influenced by federal rules, state rules, cargo, and contracts.</p></div><div className="bg-slate-900 border border-slate-800 rounded-2xl p-6"><FileCheck2 className="text-emerald-400 mb-4" /><h2 className="text-xl font-bold text-white mb-3">Insurance filings</h2><p className="text-slate-400 leading-relaxed">An insurance filing communicates financial responsibility to the relevant authority. BMC-91X, BMC-34, BOC-3, and state filings are separate topics and should not be treated as interchangeable.</p></div><div className="bg-slate-900 border border-slate-800 rounded-2xl p-6"><CheckCircle2 className="text-amber-400 mb-4" /><h2 className="text-xl font-bold text-white mb-3">Cargo and contracts</h2><p className="text-slate-400 leading-relaxed">Cargo limits may be required by a broker, shipper, commodity, or contract even when a different limit applies to a regulatory filing.</p></div></div></section>

    <section className="max-w-7xl mx-auto px-6 py-16 grid lg:grid-cols-2 gap-12"><div><h2 className="text-3xl font-black text-white mb-5">Information to prepare</h2><ul className="space-y-3 text-slate-300">{['DOT and MC numbers, if applicable', 'Legal business name and address', 'Equipment type, vehicle values, and VINs', 'Cargo and commodities transported', 'Operating radius and states traveled', 'Driver experience, MVRs, and loss history'].map(item => <li key={item} className="flex gap-3"><CheckCircle2 className="w-5 h-5 text-emerald-400 shrink-0" />{item}</li>)}</ul></div><div><h2 className="text-3xl font-black text-white mb-5">Continue your research</h2><div className="space-y-3"><Link href="/trucking-insurance-requirements" className="block border border-slate-700 rounded-xl p-4 hover:border-blue-400 font-bold text-white">Commercial trucking requirements <ArrowRight className="inline w-4 h-4 ml-2" /></Link><Link href="/dot-insurance-lookup" className="block border border-slate-700 rounded-xl p-4 hover:border-blue-400 font-bold text-white">DOT insurance lookup <ArrowRight className="inline w-4 h-4 ml-2" /></Link><Link href="/box-truck-insurance" className="block border border-slate-700 rounded-xl p-4 hover:border-blue-400 font-bold text-white">Box truck insurance guide <ArrowRight className="inline w-4 h-4 ml-2" /></Link><Link href="/hot-shot" className="block border border-slate-700 rounded-xl p-4 hover:border-blue-400 font-bold text-white">Hot shot insurance guide <ArrowRight className="inline w-4 h-4 ml-2" /></Link></div></div></section>
  </main><Footer /></div>;
}
