/**
 * GENERATE ROUTES SQL
 * Usage: node scripts/generate_routes_sql.mjs > seed_routes_full.sql
 */

const STATES = [
    { code: 'AL', name: 'Alabama' }, { code: 'AK', name: 'Alaska' }, { code: 'AZ', name: 'Arizona' }, { code: 'AR', name: 'Arkansas' }, 
    { code: 'CA', name: 'California' }, { code: 'CO', name: 'Colorado' }, { code: 'CT', name: 'Connecticut' }, { code: 'DE', name: 'Delaware' }, 
    { code: 'FL', name: 'Florida' }, { code: 'GA', name: 'Georgia' }, { code: 'HI', name: 'Hawaii' }, { code: 'ID', name: 'Idaho' }, 
    { code: 'IL', name: 'Illinois' }, { code: 'IN', name: 'Indiana' }, { code: 'IA', name: 'Iowa' }, { code: 'KS', name: 'Kansas' }, 
    { code: 'KY', name: 'Kentucky' }, { code: 'LA', name: 'Louisiana' }, { code: 'ME', name: 'Maine' }, { code: 'MD', name: 'Maryland' }, 
    { code: 'MA', name: 'Massachusetts' }, { code: 'MI', name: 'Michigan' }, { code: 'MN', name: 'Minnesota' }, { code: 'MS', name: 'Mississippi' }, 
    { code: 'MO', name: 'Missouri' }, { code: 'MT', name: 'Montana' }, { code: 'NE', name: 'Nebraska' }, { code: 'NV', name: 'Nevada' }, 
    { code: 'NH', name: 'New Hampshire' }, { code: 'NJ', name: 'New Jersey' }, { code: 'NM', name: 'New Mexico' }, { code: 'NY', name: 'New York' }, 
    { code: 'NC', name: 'North Carolina' }, { code: 'ND', name: 'North Dakota' }, { code: 'OH', name: 'Ohio' }, { code: 'OK', name: 'Oklahoma' }, 
    { code: 'OR', name: 'Oregon' }, { code: 'PA', name: 'Pennsylvania' }, { code: 'RI', name: 'Rhode Island' }, { code: 'SC', name: 'South Carolina' }, 
    { code: 'SD', name: 'South Dakota' }, { code: 'TN', name: 'Tennessee' }, { code: 'TX', name: 'Texas' }, { code: 'UT', name: 'Utah' }, 
    { code: 'VT', name: 'Vermont' }, { code: 'VA', name: 'Virginia' }, { code: 'WA', name: 'Washington' }, { code: 'WV', name: 'West Virginia' }, 
    { code: 'WI', name: 'Wisconsin' }, { code: 'WY', name: 'Wyoming' }
];

console.log(`-- SEED DATA: 2,500 Route Permutations`);
console.log(`-- Generated by scripts/generate_routes_sql.mjs`);
console.log(`\nINSERT INTO routes (slug, origin_code, destination_code, origin_name, destination_name, meta_title, status) VALUES`);

let count = 0;
const total = STATES.length * (STATES.length - 1); // ex. self

const output = [];

STATES.forEach(origin => {
    STATES.forEach(dest => {
        if (origin.code === dest.code) return; // Skip internal routes for now (or keep them?) 
        // Keeping them is fine for "Intrastate" logic but let's stick to Interstate for High Value
        if (origin.code === dest.code) return;

        const slug = `${origin.name.toLowerCase().replace(/ /g, '-')}-to-${dest.name.toLowerCase().replace(/ /g, '-')}-truck-insurance`;
        const title = `${origin.name} to ${dest.name} Truck Insurance Requirements`;
        
        output.push(`(
  '${slug}', 
  '${origin.code}', 
  '${dest.code}', 
  '${origin.name}', 
  '${dest.name}', 
  '${title}',
  'DRAFT'
)`);
    });
});

console.log(output.join(',\n') + ';');
